### ISSUE TITLE
Mark homework 1, exercise 3 of Alex-Schmidt

### ISSUE THREAD

**Issue by ajschmidt01** [ajschmidt01/stat679work#2]
@cecileane 

**Last commit:**
https://github.com/ajschmidt01/stat679work/commit/bfa6fb03dc69d11840cc1efe68aa1ffa2a93d989

**HW 1.3**
I uploaded the script file (_summarizeSNaQres.sh_) and resulting csv file (_snaqResSummary.csv_). I also uploaded the readme files from the root directory, script directory, and results directory.

**Comment by mkamenet3** [comment]
@ajschmidt01 

Hi Alex!

Great job with the README file. I really liked how you included how you got the data in the first place in everything from the git clone to the cp command.  In the readme in the 'scripts' directory, it may be helpful to also include the exact command on how to run each of the scripts.  In 'normalizeFileNames.sh', you start by setting your working directory to be up one level.  I was wondering if maybe you don't need to do that? So I see you have 'cd ${wd}/data/hw1-snaqTimeTests/$dir' and then start a loop to rename the files. However, I think you should be able to just 'echo ../data/hw1-snaqTimeTests/$dir' within the loop and avoid these steps. That being said, your annotation of all of your steps was super helpful and very clear. I also really liked how you echoed the file names as a check. I think it would also be helpful if maybe you add a 'data' folder into your directory structure and include the files in there that you have referenced. Given that these files are pretty small, it's just an idea.

With respect to summarizeSNaQres.sh, I really liked the error check that you echo if you are running the code from a wrong directory.  Also the warning for the csv file being replaced is super helpful.  

Lastly, in your readme you mention that the normalizing script needs to be run before the summarize script. You can actually code this dependency in. So in your ''summarizeSNaQres.sh' script, at the very top you can add 'source normalizeFileNames.sh' and then it will automatically run the normalizing script prior to running the summarize script. Great job overall!

**Comment by zhou325** [comment]
Hi Alex,

Nice work!  I ran your script successfully in my computer.  I like your `readme` file, which gives an overview as well as detailed description of what you have in every directory.  Besides, you also give instructions on how to reproduce the result, which is helpful for me when I ran your script.

In your script `summarizeSNaQres.sh`, it is great that you start your code with safe options and permissions.  I like your error check and the error messages.  This is really helpful for readers to figure out what is going on when they cannot successfully run the script.  And I also like the way you name your variables, because it does help me to understand what the value of this variable is likely to be at the first glance.  Besides, your comments are all very clear and understandable. 

In your script, you make a really good use of `gsed`, and I learned a lot from the way you use that.  The result table I got from your script seems correct and complete.  When to get variables `under3460`, `under 3450` and `under3440`, you use `gsed` to match every digit in the number.  This is great but I guess to match the number digit by digit is a little bit complicated and therefore, it might be lack of extensive applicability.  I would like to recommend you use `if` statements and checks to  compare the numbers directly.  And then, use arithmetic expansion to count the numbers that meet our requirement.

Overall, you did a great job in this homework, and I really learned a lot from your work.
Thank you!

Youjia
