### ISSUE TITLE
Mark homework 2 of Alex-Schmidt

### ISSUE THREAD

**Issue by ajschmidt01** [ajschmidt01/stat679work#3]
@cecileane

**Latest commit**
a5221add2c692f7609852d02b24429b417e890fb

**Explanation**
This commit includes necessary files for homework 2. Specifically it includes:

1. The readme file from the root directory that explains the project and subdirectories.
2. The script/module (temp_energy_merge.py) and associated readme file.
3. The .csv results of the merging procedure (temp_energy_merge.csv) and associated readme file.
4. The two original data files (energy.csv, and waterTemperature.csv) and associated readme file.

**Comment by cecileane** [comment]
Hi Alex,

Very nice job! Your work was easy to go through, your code is very human-readable, and your script worked. More details below.

## overall presentation

I like that you organized your project with different folders for your script and input/output data files. Your readme files are excellent: with data provenance, assumptions (and which ones are checked), and very clear instructions to run the script. You made great use of markdown style.

## running your script

I did this from the `script` folder, within python, trying to give the full path to data files, but that didn't work unfortunately:

```python
import temp_energy_merge as m
help(m)
di = "../data/" # directory for data files
m.merge(di+"waterTemperature.csv", di+"energy.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ane/Documents/private/st679/studenthw/alexSchmidt/hw2/scripts/temp_energy_merge.py", line 47, in merge
    assert dir == "data", "Please run module from the data directory."
AssertionError: Please run module from the data directory.
```

The error message was definitely helpful: I had no choice but follow your instructions :)
I don't really understand why the script could not use file names with their paths. The utilities to `open` a file will work just fine if on file names with paths. Might this be because the file name for the output is hard-coded as `../results/temp_energy_merge.csv`, and so the script needs the directory `../results/` to exist? If so, you could have setup your function arguments differently to simplify both issues (any input directory, and user-defined output file name). You could have replaced the option `stdout=True` by `outputfile=None`. The function could then have tested to see if `outputfile==None` (which would be True by default). If so, the function would send the output to STDOUT. If not, the function would send the output to file name "outputfile", and it's the user's responsibility to give a correct path for the file.

Anyway, things worked when I complied with your instructions.

It would be great if the script could be applied from the command line (the shell), because the shell makes better use of stdout (we can redirect it to a file or pipe it to a command). The extra step for this would have been to read the arguments given to the script, with the argparse module for instance.

In your output, I believe that the energy value is written one line below where it should (just one hour late). For instance, instead of producing this:

    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.3,

your code produces this (which makes sense too):

    14,07/29/16 11:26:34 PM,73.45,
    15,07/30/16 12:26:34 AM,72.3,9.468

## about your code

You included a docstring for the module and for your function, and many comments, fantastic job.

Your code would benefit from being broken down into separate functions. Your one function `merge` does everything: read the temperature file, read the energy file, and then write the output file.

You have a great use of `assert` statements or `raise Exception()` to send errors (when appropriate) with helpful messages.

Great work getting the header line(s) (and number of such lines) from the input temperature data.
